[UC09#85 ] Implements the logic to access New Exchange Page from Card Details Page
alessioarcara/project_sweng pull request #112
Opened 2023-02-01 20:41 UTC by Matte0Sacc0

In this PR, according to what requested in issue #85, has been implemented the logic that passes the PlaceController into the NewExchangePlace and allows the user to navigate from the Card Details Page to the page where will be isplayed the UI to propose exchanges to the selected user.

2023-02-03 23:15 UTC, alessioarcara requested changes
Just make some minor changes. Thank you @Matte0Sacc0

2023-02-03 23:15 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/client/views/CardViewImpl.java
> +        presenter.goTo(new NewExchangePlace(selectedCardId, receiverUserEmail));
Naming should be representative of what the function does. I suggest you to rename the function to `onClickExchangeButton`

2023-02-03 23:15 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/client/views/HomeViewImpl.java
> +
Can you explain the reason behind the implementation of an interface and method in the HomeView?

2023-02-03 23:15 UTC, alessioarcara commented on src/test/java/com/aadm/cardexchange/client/NewExchangeActivityTest.java
> +        expectLastCall();
you can omit `expectLastCall` in void methods

2023-02-03 23:15 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/client/widgets/UserListWidget.java
> +        if (showExchangeButton) table.setWidget(numRows, 2, button);
I suggest you keep the derived function locally within the constructor to reduce the risk of calling it in other parts of the class. Instead, create a button and pass it to addRow with the click handler already set.

2023-02-04 11:09 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/client/views/HomeViewImpl.java
> +
This reference is used in method `addRow` of file UserListWidget.Java and needs to be passed from Home because it's used in the Card Details page that gets its references back from HomeViewImpl.Java
The function is used in the Exchange Button placed in each row coresponding to each single user in the two users list in Card Details Page

2023-02-04 11:09 UTC, Matte0Sacc0 commented on src/test/java/com/aadm/cardexchange/client/NewExchangeActivityTest.java
> +        expectLastCall();
Thanks for the tip, I'm fixing it right now

2023-02-04 11:11 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/client/widgets/UserListWidget.java
> +        if (showExchangeButton) table.setWidget(numRows, 2, button);
Perhaps you suggest to create the Button right before passing line 47 in this snippet?

2023-02-05 00:06 UTC, merged