[UC09#111] Implemented GetOwnedPhysicalCardByCardId RPC to allow the user to view card ownership information
alessioarcara/project_sweng pull request #116
Opened 2023-02-03 21:04 UTC by alessioarcara

This PR implements #111 and allows the user to view the owners of a card. Also I have refactored the models by removing the decorator pattern from Card and PhysicalCard and using simple subclasses to reduce unnecessary complexity. I added two additional models, PhysicalCardWithName and PhysicalCardWithEmail, which provide the necessary information for the client to correctly populate the requested pages. 
Least but not last, I have removed the boolean fields of the subclasses and rethought the original model as an aggregation of `variants` (using a set collection). This allows the model to be more flexible, open to extensions but closed to modifications. 
This is an introduction to the major changes that will be coming in a subsequent PR #115.

Supplied with coverage for testing.

2023-02-03 21:48 UTC, dstops commented on src/main/java/com/aadm/cardexchange/client/widgets/GameFiltersWidget.java
>          gameBooleanFieldsMap.put(Game.MAGIC, Arrays.asList("hasFoil", "isAlternative", "isFullArt", "isPromo", "isReprint"));
You refactor name of Pokemon main properties, why did you leave the magic one like before?

2023-02-03 22:31 UTC, dstops commented on src/main/java/com/aadm/cardexchange/server/ListenerImpl.java
>          System.out.println("*** Loading data from file. ***");
remove System.out.println

2023-02-03 22:44 UTC, dstops reviewed
Good Job! 
I would only recommend using, when available with the next merge, the randomised methods of game/status creation of physical cards for improve testing, especially in DecksActivityTest, DeckServiceTest, GsonSerializerTest and PhysicalCardTest. Now we are waiting for Matteo checks.

2023-02-04 11:01 UTC, Matte0Sacc0 requested changes
I've noticed a massive refactor inthis code, 73 files changed are not the ideal number, maybe the entyre refactor could have been moved to another branch and another PR. 
A part from that I've left some tips in the code for naming consistency that are not impactful for the review. 

I only request to change the catch phrase of an error in ExchangeServiceImpl.java, and the reason is that this error should indicate the user what's really happening

2023-02-04 11:01 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/server/services/ExchangeServiceImpl.java
>              throw new InputException("Invalid senderPhysicalCards list");
There is a typo error where you're checking `checkPcardListConsistency(receiverPhysicalCards)` but you're giving an output error saying ` throw new InputException("Invalid senderPhysicalCards list")`

2023-02-04 11:01 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/server/services/DeckServiceImpl.java
> +        List<PhysicalCardWithEmail> pDecoratedCards = new ArrayList<>();
I suggest to call the object with a more appropriate name, take `pCardsWithEmail` as an example

2023-02-04 11:01 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/server/services/DeckServiceImpl.java
> +        List<PhysicalCardWithName> pDecoratedCards = new ArrayList<>();
Considering there is no more PhysicalCardDecorator i suggest to use a better typo for variables and objects naming.
`pDecoratedCards` should be `pCardsWithName` in advance to be the clearest for future maintenance

2023-02-04 11:01 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/client/widgets/PhysicalCardWidget.ui.xml
>          <g:Button title="Rimuovi carta dal mazzo" styleName="{style.deleteButton}" ui:field="deleteButton">X</g:Button>
Here a quick tip not impactful for the review... I'd better love using html graphical references codes in buttons symbols. The X char could be replaced with the code `&#10006;`

2023-02-04 11:01 UTC, Matte0Sacc0 commented on src/main/java/com/aadm/cardexchange/client/widgets/GameFiltersWidget.java
>          gameBooleanFieldsMap.put(Game.MAGIC, Arrays.asList("hasFoil", "isAlternative", "isFullArt", "isPromo", "isReprint"));
@dstops I think he just left Magic propertier named as before because the refactor has consisted in leaving the bare name of each property. To be clearer the Pokemon object in Json files has a row of properties named as in the refactor, otherwise the Magic object in Json files already has the correct naming

2023-02-04 13:26 UTC, Matte0Sacc0 approved these changes
Good Job!!!

2023-02-04 13:31 UTC, merged