[UC14#118] Create RPC to check if pCard exist in owned deck by idCard
alessioarcara/project_sweng pull request #122
Opened 2023-02-04 22:43 UTC by dstops

This PR implements #18, adding the necessary RPC to check by idCard, Game and token if the Pcard of that idcard in parameter real exist in "Owned" deck of user, find extract mail by token in login map.

Supplied with coverage for unit testing.

2023-02-07 09:13 UTC, alessioarcara requested changes
I would suggest you to redo the RPC, in order to align it with our needs.

2023-02-07 09:13 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/client/widgets/AddCardToDeckModalWidget.ui.xml
> +
Please remove this change, as the CSS for the modal has already been resolved

2023-02-07 09:13 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/server/services/ExchangeServiceImpl.java
> +            System.out.println(pCard.getCardId());
Please remove the println statement from the code

2023-02-07 09:13 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/server/services/ExchangeServiceImpl.java
> +    }
Could you change this RPC to an RPC for authorized users that utilizes the RPC from issue #140 and provides a list of physical cards desired by users, along with the ID of my physical card for each of these cards if I possess it (based on the first match), so that it can be checked directly on the proposal page? You can create a new derived class or class payload for this RPC

2023-02-09 14:54 UTC, dstops commented
Done change requested.

2023-02-10 14:29 UTC, alessioarcara requested changes
Test code is just important as production code. It is not a second-class citizen. It must be kept as clean as production code.
I have commented out the portions of code related to tests that need to be refactored. I suggest to think about a simple, well-defined success case

2023-02-10 17:16 UTC, dstops commented
Thank you @alessioarcara. Now tests for this RPC are more clean and more understandable.

2023-02-11 23:55 UTC, Matte0Sacc0 approved these changes
Great Job!!!

2023-02-11 23:56 UTC, alessioarcara approved these changes
Approved this PR. Great work! 🎉

2023-02-12 00:04 UTC, merged