[UC19#94#131] Create RPC to get received / send list proposal
alessioarcara/project_sweng pull request #168
Opened 2023-02-07 01:45 UTC by dstops

This PR implements #94 (Create RPC to get exchange proposal received list) and #131 (Create RPC to get exchange proposal send list), adding the necessary RPC to check by  token.
I improved also Proposal model adding String date attribute.

Supplied with coverage for unit testing.

2023-02-07 08:54 UTC, alessioarcara requested changes
pointed out some points that, imho, need to be fixed

2023-02-07 08:54 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/server/services/ExchangeServiceImpl.java
> +    }
You are using an XOR check to avoid both true or false conditions, and then inside an if statement to choose which branch of the if statement to enter. In my opinion, you could easily keep it separated into two separate methods, since in the end they behave differently. The code is repeated and in my opinion this needs to be fixed

2023-02-07 08:54 UTC, alessioarcara commented on src/main/java/com/aadm/cardexchange/shared/models/Proposal.java
>      }
Instead of passing a date, could you not generate a date directly in the constructor?

2023-02-09 22:31 UTC, dstops commented
Changes required done. Fix data problem.

2023-02-10 01:15 UTC, alessioarcara approved these changes
Thanks for addressing the problems pointed out, I can now consider this approved 👌🏻

2023-02-10 01:16 UTC, merged